# config
cover: /images/mountain-1.jpg
logo: 
bio: "I'm an unashamed idealist, but I'm not afraid to change my opinions. I love creating beautiful things. interfaces, apis, music. ideas."

# Content
excerpt_link: Read More

# Miscellaneous
rss:
